export const RICH_TEXT_CONTENT = [
  "font-sans text-base leading-[var(--rc-leading-normal)] text-fg break-words",
  "[&>*+*]:mt-3",
  "[&_h2]:font-display [&_h2]:font-semibold [&_h2]:text-fg",
  "[&_h2]:text-xl [&_h2]:tracking-display",
  "[&_h3]:font-display [&_h3]:font-semibold [&_h3]:text-fg",
  "[&_h3]:text-lg [&_h3]:tracking-tight",
  "[&_ul]:list-disc [&_ul]:pl-6 [&_ol]:list-decimal [&_ol]:pl-6",
  "[&_li]:pl-1 [&_li+li]:mt-1 [&_li>*+*]:mt-1 [&_li]:marker:text-fg-subtle",
  "[&_blockquote]:border-l-2 [&_blockquote]:border-border-strong [&_blockquote]:pl-4",
  "[&_blockquote]:text-fg-muted [&_blockquote>*+*]:mt-2",
  "[&_:not(pre)>code]:rounded-sm [&_:not(pre)>code]:bg-surface-raised",
  "[&_:not(pre)>code]:px-1.5 [&_:not(pre)>code]:py-0.5 [&_:not(pre)>code]:font-mono",
  "[&_:not(pre)>code]:text-[0.9em] [&_:not(pre)>code]:text-fg-muted",
  "[&_pre]:overflow-x-auto [&_pre]:rounded-lg [&_pre]:border [&_pre]:border-border",
  "[&_pre]:bg-surface-raised [&_pre]:p-3 [&_pre]:font-mono [&_pre]:text-xs",
  "[&_pre]:leading-relaxed [&_pre]:text-fg",
  "[&_pre]:outline-none [&_pre:focus-visible]:ring-2 [&_pre:focus-visible]:ring-ring",
  "[&_a]:rounded-sm [&_a]:text-accent-text [&_a]:underline [&_a]:decoration-1",
  "[&_a]:underline-offset-[0.2em] [&_a:hover]:decoration-2 [&_a]:outline-none",
  "[&_a:focus-visible]:ring-2 [&_a:focus-visible]:ring-ring",
  "[&_strong]:font-bold [&_hr]:my-4 [&_hr]:border-border",
].join(" ");
