#!/usr/bin/env node
import { readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";

const requireFromApp = createRequire(`${process.cwd()}/`);
const postcss = requireFromApp("postcss");
const tailwind = requireFromApp("@tailwindcss/postcss");

const input = process.argv[2] ?? "global.css";
const output = process.argv[3] ?? "generated.css";

const css = readFileSync(input, "utf8");
const out = await postcss([tailwind({ base: process.cwd() })]).process(css, {
  from: input,
});

let flat = out.css;

const initials = [];
flat = flat.replace(/@property\s+(--[\w-]+)\s*\{[^}]*?\}/g, (block, name) => {
  const initial = /initial-value:\s*([^;}]+)/.exec(block)?.[1]?.trim();
  if (initial) initials.push(`  ${name}: ${initial};`);
  return "";
});

if (initials.length > 0) {
  flat = `:root {\n${initials.join("\n")}\n}\n${flat}`;
}

flat = flat.replace(/@layer properties;\n?/g, "");
const layerAt = flat.indexOf("@layer properties {");
if (layerAt !== -1) {
  let depth = 0;
  let end = layerAt;
  for (let i = flat.indexOf("{", layerAt); i < flat.length; i++) {
    if (flat[i] === "{") depth++;
    if (flat[i] === "}") depth--;
    if (depth === 0) {
      end = i + 1;
      break;
    }
  }
  flat = flat.slice(0, layerAt) + flat.slice(end);
}

const declaredVars = () => new Set([...flat.matchAll(/(--[\w-]+)\s*:/g)].map((m) => m[1]));
for (let pass = 0; pass < 5; pass++) {
  const declared = declaredVars();
  const next = flat.replace(
    /var\((--[\w-]+)\s*(?:,\s*([^()]*(?:\([^()]*\)[^()]*)*))?\)/g,
    (whole, name, fallback) => {
      if (declared.has(name)) return whole;
      return fallback !== undefined ? fallback.trim() : whole;
    },
  );
  if (next === flat) break;
  flat = next;
}
flat = flat.replace(/^\s*[\w-]+:\s*;\n/gm, "");

const declared = declaredVars();
const orphans = [...new Set([...flat.matchAll(/var\((--[\w-]+)/g)].map((m) => m[1]))].filter(
  (name) => !declared.has(name),
);
if (orphans.length > 0) {
  console.error(`vars used with no declaration and no fallback: ${orphans.join(", ")}`);
  process.exit(1);
}

writeFileSync(
  output,
  `/* Generated by rivocode-ui-native-css from ${input}. Do not edit. */\n${flat}`,
);
console.log(`${output}: ${flat.length} bytes, ${initials.length} @property became :root`);
