/* ---------------------------------------------------------------------------
 * How many pieces exist in React Native
 *
 * Counted from the guide's parity table, not written here. The table is
 * generated by `scripts/native-parity.ts` and `bun run check:parity` holds it
 * against `native/src/index.ts`: it cannot say a piece is missing after the
 * piece has arrived. A number derived from it is born with that guarantee for
 * free.
 *
 * This matters because the home page once had a hand-written digit, and it
 * went stale twice: it stuck at 292 and then at 348 while the suite reached
 * 552. The native queue moves every week, so this one would be the next to lie.
 *
 * The count moved to the build, out of the browser: doing the math here forced
 * the home page to load the whole guide (30 KB of table) to print two digits.
 * The `catalogIndex` in `vite.config.ts` reads the same table.
 * ------------------------------------------------------------------------- */

export { NATIVE_PIECES } from 'virtual:catalog-index'
