/** The icon gallery collection, generated by the plugin in vite.config.ts. */
declare module 'virtual:icon-gallery' {
  const icons: Record<string, Array<[string, Record<string, string>]>>
  export default icons
}

/** The catalog index, generated by the plugin in vite.config.ts. */
declare module 'virtual:catalog-index' {
  export const DOC_INDEX: Array<{ name: string; family: string; summary: string }>
  export const NATIVE_PIECES: number
}

/** Per piece, the loader for the props of the page it lives on; generated in vite.config.ts. */
declare module 'virtual:component-props' {
  export const LOADERS: Record<
    string,
    () => Promise<{ default: Record<string, import('./prop-types').Piece> }>
  >
}

/** The whole house CSS, with imports resolved; generated in vite.config.ts. */
declare module 'virtual:house-css' {
  const css: string
  export default css
}
