/**
 * Restores the accents to Portuguese prose.
 *
 * The catalog was written without accents, and without them it reads as
 * sloppiness on a page made for a client. Code is left untouched: fenced
 * blocks, backtick spans and whatever looks like an identifier keep their exact
 * bytes, because `nao` inside a prop name is not a typo.
 *
 * The `e` -> `é` case is not solved by dictionary, because one is the
 * conjunction and the other is the verb. It goes only through context rules,
 * and whatever the rules do not recognize stays as is and is reported for a
 * person to read.
 */

/**
 * The repository's accent dictionary.
 *
 * Exported because there is a second reader: the `test/accents.test.ts` guard,
 * which demands accents in the text the library writes on the SCREEN. It kept
 * its own list of twenty-two words, and a list of twenty-two inside a house
 * that already had one of two hundred and eighty could only age worse - that
 * is how "Navegacao" reached the interface.
 */
export const WORDS: Record<string, string> = {
  nao: "não",
  acao: "ação",
  acoes: "ações",
  botao: "botão",
  botoes: "botões",
  pagina: "página",
  paginas: "páginas",
  padrao: "padrão",
  padroes: "padrões",
  opcao: "opção",
  opcoes: "opções",
  codigo: "código",
  usuario: "usuário",
  usuarios: "usuários",
  voce: "você",
  ja: "já",
  tambem: "também",
  alem: "além",
  apos: "após",
  atraves: "através",
  proxima: "próxima",
  proximo: "próximo",
  proprio: "próprio",
  propria: "própria",
  proprios: "próprios",
  proprias: "próprias",
  unico: "único",
  unica: "única",
  unicos: "únicos",
  unicas: "únicas",
  multipla: "múltipla",
  multiplo: "múltiplo",
  numero: "número",
  numeros: "números",
  minimo: "mínimo",
  maximo: "máximo",
  titulo: "título",
  titulos: "títulos",
  rotulo: "rótulo",
  rotulos: "rótulos",
  icone: "ícone",
  icones: "ícones",
  conteudo: "conteúdo",
  area: "área",
  arvore: "árvore",
  arvores: "árvores",
  areas: "áreas",
  invalido: "inválido",
  valido: "válido",
  obrigatoria: "obrigatória",
  obrigatorio: "obrigatório",
  automatico: "automático",
  automatica: "automática",
  semantico: "semântico",
  semantica: "semântica",
  semanticos: "semânticos",
  semanticas: "semânticas",
  generico: "genérico",
  generica: "genérica",
  basico: "básico",
  basica: "básica",
  grafico: "gráfico",
  graficos: "gráficos",
  possivel: "possível",
  impossivel: "impossível",
  disponivel: "disponível",
  indisponivel: "indisponível",
  responsavel: "responsável",
  acessivel: "acessível",
  acessiveis: "acessíveis",
  legivel: "legível",
  legiveis: "legíveis",
  visivel: "visível",
  visiveis: "visíveis",
  util: "útil",
  uteis: "úteis",
  dificil: "difícil",
  facil: "fácil",
  movel: "móvel",
  ancora: "âncora",
  referencia: "referência",
  referencias: "referências",
  preferencia: "preferência",
  preferencias: "preferências",
  experiencia: "experiência",
  consequencia: "consequência",
  consequencias: "consequências",
  sequencia: "sequência",
  frequencia: "frequência",
  variavel: "variável",
  variaveis: "variáveis",
  estavel: "estável",
  periodo: "período",
  periodos: "períodos",
  memoria: "memória",
  historia: "história",
  historico: "histórico",
  descricao: "descrição",
  descricoes: "descrições",
  selecao: "seleção",
  navegacao: "navegação",
  informacao: "informação",
  informacoes: "informações",
  aplicacao: "aplicação",
  aplicacoes: "aplicações",
  emissao: "emissão",
  atencao: "atenção",
  posicao: "posição",
  posicoes: "posições",
  transicao: "transição",
  animacao: "animação",
  animacoes: "animações",
  validacao: "validação",
  formatacao: "formatação",
  configuracao: "configuração",
  instalacao: "instalação",
  personalizacao: "personalização",
  documentacao: "documentação",
  organizacao: "organização",
  operacao: "operação",
  duracao: "duração",
  direcao: "direção",
  altura: "altura",
  ate: "até",
  tres: "três",
  varias: "várias",
  varios: "vários",
  ultima: "última",
  ultimo: "último",
  primeiro: "primeiro",
  ideia: "ideia",
  criterio: "critério",
  criterios: "critérios",
  contrario: "contrário",
  necessario: "necessário",
  necessaria: "necessária",
  cabecalho: "cabeçalho",
  cabecalhos: "cabeçalhos",
  espaco: "espaço",
  espacos: "espaços",
  servico: "serviço",
  servicos: "serviços",
  comeco: "começo",
  preco: "preço",
  precos: "preços",
  terco: "terço",
  atalho: "atalho",
  duvida: "dúvida",
  duvidas: "dúvidas",
  saida: "saída",
  saidas: "saídas",
  entrada: "entrada",
  familia: "família",
  familias: "famílias",
  hierarquia: "hierarquia",
  visao: "visão",
  versao: "versão",
  versoes: "versões",
  extensao: "extensão",
  dimensao: "dimensão",
  decisao: "decisão",
  decisoes: "decisões",
  precisao: "precisão",
  revisao: "revisão",
  divisao: "divisão",
  ordem: "ordem",
  imagem: "imagem",
  imagens: "imagens",
  margem: "margem",
  origem: "origem",
  porcentagem: "porcentagem",
  mensagem: "mensagem",
  mensagens: "mensagens",
  contagem: "contagem",
  linguagem: "linguagem",
  so: "só",
  entao: "então",
  formulario: "formulário",
  sobreposicao: "sobreposição",
  peca: "peça",
  pecas: "peças",
  proposito: "propósito",
  compoe: "compõe",
  secundaria: "secundária",
  secundario: "secundário",
  obvio: "óbvio",
  silencio: "silêncio",
  inicio: "início",
  pratico: "prático",
  estatico: "estático",
  dinamico: "dinâmico",
  publico: "público",
  especifico: "específico",
  tipico: "típico",
  rapido: "rápido",
  analise: "análise",
  parametro: "parâmetro",
  parametros: "parâmetros",
  metodo: "método",
  modulo: "módulo",
  calendario: "calendário",
  relatorio: "relatório",
  diretorio: "diretório",
  temporario: "temporário",
  comentario: "comentário",
  vocabulario: "vocabulário",
  heranca: "herança",
  cabeca: "cabeça",
  crianca: "criança",
  diferenca: "diferença",
  diferencas: "diferenças",
  mudanca: "mudança",
  mudancas: "mudanças",
  seguranca: "segurança",
  confianca: "confiança",
  licenca: "licença",
  presenca: "presença",
  ausencia: "ausência",
  urgencia: "urgência",
  emergencia: "emergência",
  ambiguo: "ambíguo",
  ambigua: "ambígua",
  sintese: "síntese",
  tecnico: "técnico",
  tecnica: "técnica",
  logico: "lógico",
  logica: "lógica",
  magico: "mágico",
  unicamente: "unicamente",
  anonimo: "anônimo",
  sinonimo: "sinônimo",
  economico: "econômico",
  autonomo: "autônomo",
  fenomeno: "fenômeno",
  padroniza: "padroniza",
  ninguem: "ninguém",
  alguem: "alguém",
  porem: "porém",
  armazem: "armazém",
  refem: "refém",
  convem: "convém",
  contem: "contém",
  mantem: "mantém",
  obtem: "obtém",
  provem: "provém",
  sustem: "sustém",
  ordinario: "ordinário",
  extraordinario: "extraordinário",
  arbitrario: "arbitrário",
  itens: "itens",
  indice: "índice",
  indices: "índices",
  apendice: "apêndice",
  superficie: "superfície",
  superficies: "superfícies",
  artificio: "artifício",
  exercicio: "exercício",
  beneficio: "benefício",
  oficio: "ofício",
  edificio: "edifício",
  prejuizo: "prejuízo",
  juizo: "juízo",
  raiz: "raiz",
  pais: "país",
  paises: "países",
  tras: "trás",
  atras: "atrás",
  apenas: "apenas",
  avancar: "avançar",
  avanca: "avança",
  comecar: "começar",
  comeca: "começa",
  alcanca: "alcança",
  alcancar: "alcançar",
  faz: "faz",
  reforcar: "reforçar",
  reforca: "reforça",
  esforco: "esforço",
  almoco: "almoço",
  audiencia: "audiência",
  ciencia: "ciência",
  paciencia: "paciência",
  transparencia: "transparência",
  aparencia: "aparência",
  ocorrencia: "ocorrência",
  interferencia: "interferência",
  independencia: "independência",
};

/* Where `e` is the verb and not the conjunction. Each rule describes a context
 * in which the reading is not ambiguous: after a period, before an article, and
 * so on. Whatever does not match stays as is; erring on the side of less is
 * recoverable. */
const VERB: Array<[RegExp, string]> = [
  [/\bnao e\b/g, "não é"],
  [/\bque e\b/g, "que é"],
  [/\bisso e\b/g, "isso é"],
  [/\bisto e\b/g, "isto é"],
  [/\bele e\b/g, "ele é"],
  [/\bela e\b/g, "ela é"],
  [/\beste e\b/g, "este é"],
  [/\besta e\b/g, "esta é"],
  [/\besse e\b/g, "esse é"],
  [/\bessa e\b/g, "essa é"],
  [/\bqual e\b/g, "qual é"],
  [/\bja e\b/g, "já é"],
  [/\btambem e\b/g, "também é"],
  [/\be assim que\b/g, "é assim que"],
  [/\be o unico\b/g, "é o único"],
  [/\be a unica\b/g, "é a única"],
  [/\be o contrario\b/g, "é o contrário"],
  [/\be de proposito\b/g, "é de propósito"],
];

/** Applies a function only to prose, leaving code blocks and code spans untouched. */
function proseOnly(text: string, apply: (chunk: string) => string) {
  // A link target joins the list of untouched spans along with code:
  // accenting `/instalacao` silently breaks the address.
  const parts = text.split(/(```[\s\S]*?```|`[^`\n]*`|<[^>]+>|\]\([^)]*\)|https?:\/\/\S+)/g);
  return parts.map((part, index) => (index % 2 === 0 ? apply(part) : part)).join("");
}

function keepCase(original: string, fixed: string) {
  if (original[0] === original[0]?.toUpperCase()) {
    return fixed[0]!.toUpperCase() + fixed.slice(1);
  }
  return fixed;
}

export function addAccents(text: string) {
  return proseOnly(text, (chunk) => {
    let output = chunk;

    for (const [rule, swap] of VERB) output = output.replace(rule, swap);

    output = output.replace(/\b([A-Za-zÀ-ÿ]+)\b/g, (word) => {
      const fixed = WORDS[word.toLowerCase()];
      return fixed ? keepCase(word, fixed) : word;
    });

    return output;
  });
}

/** The lines where a stray `e` survived, for a person to read. */
export function pendingLines(text: string) {
  const lines: string[] = [];
  proseOnly(text, (chunk) => {
    for (const line of chunk.split("\n")) {
      if (/\be\b/.test(line) && line.trim()) lines.push(line.trim());
    }
    return chunk;
  });
  return lines;
}
