/**
 * Devolve o acento a prosa em portugues das docs.
 *
 * O catalogo foi escrito sem acento, e sem acento ele le como desleixo numa
 * pagina feita para cliente. O codigo fica intocado: bloco cercado, trecho
 * entre crases e o que se parece com identificador guardam seus bytes exatos,
 * porque `nao` dentro de um nome de prop nao e erro de digitacao.
 *
 * O caso `e` -> `é` nao se resolve por dicionario, porque um e conjuncao e o
 * outro e o verbo. Ele passa so por regra de contexto, e o que a regra nao
 * reconhece fica como esta e sai reportado para uma pessoa ler.
 */

/**
 * O dicionario de acentos do repositorio.
 *
 * Exportado porque ha um segundo leitor: a guarda `test/acentos.test.ts`, que
 * cobra o acento no texto que a biblioteca escreve na TELA. Ela mantinha uma
 * lista propria de vinte e duas palavras, e uma lista de vinte e duas dentro
 * de uma casa que ja tinha uma de duzentas e oitenta e uma so podia envelhecer
 * pior - foi assim que "Navegacao" chegou a interface.
 */
export const WORDS: Record<string, string> = {
  nao: "não",
  acao: "ação",
  acoes: "ações",
  botao: "botão",
  botoes: "botões",
  pagina: "página",
  paginas: "páginas",
  padrao: "padrão",
  padroes: "padrões",
  opcao: "opção",
  opcoes: "opções",
  codigo: "código",
  usuario: "usuário",
  usuarios: "usuários",
  voce: "você",
  ja: "já",
  tambem: "também",
  alem: "além",
  apos: "após",
  atraves: "através",
  proxima: "próxima",
  proximo: "próximo",
  proprio: "próprio",
  propria: "própria",
  proprios: "próprios",
  proprias: "próprias",
  unico: "único",
  unica: "única",
  unicos: "únicos",
  unicas: "únicas",
  multipla: "múltipla",
  multiplo: "múltiplo",
  numero: "número",
  numeros: "números",
  minimo: "mínimo",
  maximo: "máximo",
  titulo: "título",
  titulos: "títulos",
  rotulo: "rótulo",
  rotulos: "rótulos",
  icone: "ícone",
  icones: "ícones",
  conteudo: "conteúdo",
  area: "área",
  arvore: "árvore",
  arvores: "árvores",
  areas: "áreas",
  invalido: "inválido",
  valido: "válido",
  obrigatoria: "obrigatória",
  obrigatorio: "obrigatório",
  automatico: "automático",
  automatica: "automática",
  semantico: "semântico",
  semantica: "semântica",
  semanticos: "semânticos",
  semanticas: "semânticas",
  generico: "genérico",
  generica: "genérica",
  basico: "básico",
  basica: "básica",
  grafico: "gráfico",
  graficos: "gráficos",
  possivel: "possível",
  impossivel: "impossível",
  disponivel: "disponível",
  indisponivel: "indisponível",
  responsavel: "responsável",
  acessivel: "acessível",
  acessiveis: "acessíveis",
  legivel: "legível",
  legiveis: "legíveis",
  visivel: "visível",
  visiveis: "visíveis",
  util: "útil",
  uteis: "úteis",
  dificil: "difícil",
  facil: "fácil",
  movel: "móvel",
  ancora: "âncora",
  referencia: "referência",
  referencias: "referências",
  preferencia: "preferência",
  preferencias: "preferências",
  experiencia: "experiência",
  consequencia: "consequência",
  consequencias: "consequências",
  sequencia: "sequência",
  frequencia: "frequência",
  variavel: "variável",
  variaveis: "variáveis",
  estavel: "estável",
  periodo: "período",
  periodos: "períodos",
  memoria: "memória",
  historia: "história",
  historico: "histórico",
  descricao: "descrição",
  descricoes: "descrições",
  selecao: "seleção",
  navegacao: "navegação",
  informacao: "informação",
  informacoes: "informações",
  aplicacao: "aplicação",
  aplicacoes: "aplicações",
  emissao: "emissão",
  atencao: "atenção",
  posicao: "posição",
  posicoes: "posições",
  transicao: "transição",
  animacao: "animação",
  animacoes: "animações",
  validacao: "validação",
  formatacao: "formatação",
  configuracao: "configuração",
  instalacao: "instalação",
  personalizacao: "personalização",
  documentacao: "documentação",
  organizacao: "organização",
  operacao: "operação",
  duracao: "duração",
  direcao: "direção",
  altura: "altura",
  ate: "até",
  tres: "três",
  varias: "várias",
  varios: "vários",
  ultima: "última",
  ultimo: "último",
  primeiro: "primeiro",
  ideia: "ideia",
  criterio: "critério",
  criterios: "critérios",
  contrario: "contrário",
  necessario: "necessário",
  necessaria: "necessária",
  cabecalho: "cabeçalho",
  cabecalhos: "cabeçalhos",
  espaco: "espaço",
  espacos: "espaços",
  servico: "serviço",
  servicos: "serviços",
  comeco: "começo",
  preco: "preço",
  precos: "preços",
  terco: "terço",
  atalho: "atalho",
  duvida: "dúvida",
  duvidas: "dúvidas",
  saida: "saída",
  saidas: "saídas",
  entrada: "entrada",
  familia: "família",
  familias: "famílias",
  hierarquia: "hierarquia",
  visao: "visão",
  versao: "versão",
  versoes: "versões",
  extensao: "extensão",
  dimensao: "dimensão",
  decisao: "decisão",
  decisoes: "decisões",
  precisao: "precisão",
  revisao: "revisão",
  divisao: "divisão",
  ordem: "ordem",
  imagem: "imagem",
  imagens: "imagens",
  margem: "margem",
  origem: "origem",
  porcentagem: "porcentagem",
  mensagem: "mensagem",
  mensagens: "mensagens",
  contagem: "contagem",
  linguagem: "linguagem",
  so: "só",
  entao: "então",
  formulario: "formulário",
  sobreposicao: "sobreposição",
  peca: "peça",
  pecas: "peças",
  proposito: "propósito",
  compoe: "compõe",
  secundaria: "secundária",
  secundario: "secundário",
  obvio: "óbvio",
  silencio: "silêncio",
  inicio: "início",
  pratico: "prático",
  estatico: "estático",
  dinamico: "dinâmico",
  publico: "público",
  especifico: "específico",
  tipico: "típico",
  rapido: "rápido",
  analise: "análise",
  parametro: "parâmetro",
  parametros: "parâmetros",
  metodo: "método",
  modulo: "módulo",
  calendario: "calendário",
  relatorio: "relatório",
  diretorio: "diretório",
  temporario: "temporário",
  comentario: "comentário",
  vocabulario: "vocabulário",
  heranca: "herança",
  cabeca: "cabeça",
  crianca: "criança",
  diferenca: "diferença",
  diferencas: "diferenças",
  mudanca: "mudança",
  mudancas: "mudanças",
  seguranca: "segurança",
  confianca: "confiança",
  licenca: "licença",
  presenca: "presença",
  ausencia: "ausência",
  urgencia: "urgência",
  emergencia: "emergência",
  ambiguo: "ambíguo",
  ambigua: "ambígua",
  sintese: "síntese",
  tecnico: "técnico",
  tecnica: "técnica",
  logico: "lógico",
  logica: "lógica",
  magico: "mágico",
  unicamente: "unicamente",
  anonimo: "anônimo",
  sinonimo: "sinônimo",
  economico: "econômico",
  autonomo: "autônomo",
  fenomeno: "fenômeno",
  padroniza: "padroniza",
  ninguem: "ninguém",
  alguem: "alguém",
  porem: "porém",
  armazem: "armazém",
  refem: "refém",
  convem: "convém",
  contem: "contém",
  mantem: "mantém",
  obtem: "obtém",
  provem: "provém",
  sustem: "sustém",
  ordinario: "ordinário",
  extraordinario: "extraordinário",
  arbitrario: "arbitrário",
  itens: "itens",
  indice: "índice",
  indices: "índices",
  apendice: "apêndice",
  superficie: "superfície",
  superficies: "superfícies",
  artificio: "artifício",
  exercicio: "exercício",
  beneficio: "benefício",
  oficio: "ofício",
  edificio: "edifício",
  prejuizo: "prejuízo",
  juizo: "juízo",
  raiz: "raiz",
  pais: "país",
  paises: "países",
  tras: "trás",
  atras: "atrás",
  apenas: "apenas",
  avancar: "avançar",
  avanca: "avança",
  comecar: "começar",
  comeca: "começa",
  alcanca: "alcança",
  alcancar: "alcançar",
  faz: "faz",
  reforcar: "reforçar",
  reforca: "reforça",
  esforco: "esforço",
  almoco: "almoço",
  audiencia: "audiência",
  ciencia: "ciência",
  paciencia: "paciência",
  transparencia: "transparência",
  aparencia: "aparência",
  ocorrencia: "ocorrência",
  interferencia: "interferência",
  independencia: "independência",
};

/* Onde `e` e o verbo, e nao a conjuncao. Cada regra descreve um contorno em que
 * a leitura nao e ambigua: depois de ponto, antes de artigo, e assim por
 * diante. O que nao casar fica como esta, errar para menos e recuperavel. */
const VERB: Array<[RegExp, string]> = [
  [/\bnao e\b/g, "não é"],
  [/\bque e\b/g, "que é"],
  [/\bisso e\b/g, "isso é"],
  [/\bisto e\b/g, "isto é"],
  [/\bele e\b/g, "ele é"],
  [/\bela e\b/g, "ela é"],
  [/\beste e\b/g, "este é"],
  [/\besta e\b/g, "esta é"],
  [/\besse e\b/g, "esse é"],
  [/\bessa e\b/g, "essa é"],
  [/\bqual e\b/g, "qual é"],
  [/\bja e\b/g, "já é"],
  [/\btambem e\b/g, "também é"],
  [/\be assim que\b/g, "é assim que"],
  [/\be o unico\b/g, "é o único"],
  [/\be a unica\b/g, "é a única"],
  [/\be o contrario\b/g, "é o contrário"],
  [/\be de proposito\b/g, "é de propósito"],
];

/** Aplica uma funcao so na prosa, deixando bloco e trecho de codigo intocados. */
function proseOnly(text: string, apply: (chunk: string) => string) {
  // O destino de um link entra na lista de trechos intocados junto com o
  // codigo: acentuar `/instalacao` quebra o endereco em silencio.
  const parts = text.split(/(```[\s\S]*?```|`[^`\n]*`|<[^>]+>|\]\([^)]*\)|https?:\/\/\S+)/g);
  return parts.map((part, index) => (index % 2 === 0 ? apply(part) : part)).join("");
}

function keepCase(original: string, fixed: string) {
  if (original[0] === original[0]?.toUpperCase()) {
    return fixed[0]!.toUpperCase() + fixed.slice(1);
  }
  return fixed;
}

export function addAccents(text: string) {
  return proseOnly(text, (chunk) => {
    let output = chunk;

    for (const [rule, swap] of VERB) output = output.replace(rule, swap);

    output = output.replace(/\b([A-Za-zÀ-ÿ]+)\b/g, (word) => {
      const fixed = WORDS[word.toLowerCase()];
      return fixed ? keepCase(word, fixed) : word;
    });

    return output;
  });
}

/** As linhas onde um `e` solto sobreviveu, para uma pessoa ler. */
export function pendingLines(text: string) {
  const lines: string[] = [];
  proseOnly(text, (chunk) => {
    for (const line of chunk.split("\n")) {
      if (/\be\b/.test(line) && line.trim()) lines.push(line.trim());
    }
    return chunk;
  });
  return lines;
}
