/* Gerado de src/tokens/themes/rivocode-dark.css e src/tokens/forma.css por bun run gen:temas. Nao editar. */

export const THEME_ROLES = [
  "--rc-bg",
  "--rc-surface",
  "--rc-surface-raised",
  "--rc-overlay",
  "--rc-fg",
  "--rc-fg-muted",
  "--rc-fg-subtle",
  "--rc-fg-disabled",
  "--rc-accent",
  "--rc-accent-hover",
  "--rc-accent-active",
  "--rc-accent-fg",
  "--rc-accent-text",
  "--rc-accent-subtle",
  "--rc-selected",
  "--rc-skeleton",
  "--rc-border",
  "--rc-border-strong",
  "--rc-border-disabled",
  "--rc-line-hover",
  "--rc-ring",
  "--rc-success",
  "--rc-success-fg",
  "--rc-success-text",
  "--rc-success-subtle",
  "--rc-warning",
  "--rc-warning-fg",
  "--rc-warning-text",
  "--rc-warning-subtle",
  "--rc-danger",
  "--rc-danger-fg",
  "--rc-danger-text",
  "--rc-danger-subtle",
  "--rc-info",
  "--rc-info-fg",
  "--rc-info-text",
  "--rc-info-subtle",
  "--rc-font-sans",
  "--rc-font-display",
  "--rc-font-mono",
  "--rc-text-display",
  "--rc-text-hero",
  "--rc-shadow-1",
  "--rc-shadow-2",
  "--rc-shadow-3",
  "--rc-glow-accent",
  "--rc-accent-image",
  "--rc-accent-shadow",
  "--rc-overlay-filter",
  "--rc-chart-1",
  "--rc-chart-2",
  "--rc-chart-3",
  "--rc-chart-4",
  "--rc-chart-5",
  "--rc-chart-6",
  "--rc-chart-7",
  "--rc-chart-8",
  "--rc-chart-grid",
] as const;

export const SHAPE_TOKENS = [
  "--rc-radius-sm",
  "--rc-radius-md",
  "--rc-radius-lg",
  "--rc-radius-xl",
  "--rc-radius-pill",
  "--rc-tracking-display",
  "--rc-tracking-tight",
  "--rc-duration-fast",
  "--rc-duration-base",
  "--rc-duration-slow",
  "--rc-ease",
  "--rc-ease-sheet",
  "--rc-duration-sheet",
] as const;
