const STOPWORDS = new Set([
  "a",
  "about",
  "after",
  "algo",
  "algum",
  "alguma",
  "all",
  "an",
  "and",
  "antes",
  "any",
  "ao",
  "aos",
  "aqui",
  "are",
  "as",
  "at",
  "ate",
  "be",
  "before",
  "but",
  "by",
  "cada",
  "can",
  "coisa",
  "com",
  "como",
  "da",
  "das",
  "de",
  "depois",
  "do",
  "does",
  "dos",
  "e",
  "each",
  "ela",
  "ele",
  "em",
  "entre",
  "essa",
  "esse",
  "esta",
  "estar",
  "este",
  "eu",
  "every",
  "exibir",
  "fazer",
  "for",
  "from",
  "has",
  "have",
  "how",
  "if",
  "in",
  "into",
  "is",
  "isso",
  "isto",
  "it",
  "its",
  "ja",
  "just",
  "la",
  "mais",
  "mas",
  "me",
  "more",
  "mostra",
  "mostrar",
  "much",
  "muito",
  "my",
  "na",
  "nas",
  "need",
  "no",
  "nos",
  "o",
  "of",
  "on",
  "onde",
  "only",
  "or",
  "os",
  "ou",
  "outra",
  "outro",
  "para",
  "pela",
  "pelo",
  "por",
  "pouco",
  "preciso",
  "quais",
  "qual",
  "quando",
  "que",
  "quero",
  "screen",
  "se",
  "sem",
  "ser",
  "seu",
  "show",
  "so",
  "sobre",
  "some",
  "sua",
  "tela",
  "tem",
  "ter",
  "that",
  "the",
  "their",
  "then",
  "there",
  "these",
  "this",
  "to",
  "toda",
  "todo",
  "todos",
  "um",
  "uma",
  "umas",
  "uns",
  "use",
  "usar",
  "vai",
  "vou",
  "want",
  "what",
  "when",
  "where",
  "which",
  "while",
  "who",
  "will",
  "with",
  "you",
  "your",
]);

const GLOSSARY: Record<string, string> = {
  aba: "tab",
  abas: "tabs",
  abrir: "open",
  achar: "find",
  ajuda: "help",
  anexar: "attach",
  apagar: "delete erase",
  armazenamento: "storage",
  arquivo: "file",
  arrastando: "drag dragging",
  arrastar: "drag",
  assinatura: "signature",
  assistente: "assistant",
  atalho: "shortcut",
  avaliacao: "rating",
  avancadas: "advanced",
  aviso: "notice warning",
  baixar: "download",
  botao: "button",
  busca: "search",
  buscar: "search",
  cadastro: "registration signup",
  calendario: "calendar",
  campo: "field input",
  campos: "fields",
  carregando: "loading",
  carro: "car vehicle",
  cartao: "card",
  celular: "mobile phone",
  chave: "key",
  cima: "over top",
  cliente: "customer client",
  codigo: "code",
  colar: "paste",
  coluna: "column",
  confirmar: "confirm",
  contato: "contact",
  conversa: "chat conversation",
  copiar: "copy",
  cor: "color",
  credito: "credit",
  cronograma: "schedule timeline",
  data: "date",
  desfazer: "undo",
  detalhe: "detail",
  dica: "hint tip",
  dinheiro: "money",
  direto: "inline directly",
  editar: "edit",
  endereco: "address",
  enviar: "send submit",
  erro: "error",
  escolha: "choice",
  escolher: "choose pick",
  estrelas: "stars",
  etapas: "steps",
  excluir: "delete",
  exclusao: "deletion delete",
  filtrar: "filter",
  filtro: "filter",
  formulario: "form",
  foto: "photo",
  grafico: "chart",
  grupo: "group",
  hora: "time",
  icone: "icon",
  imagem: "image",
  inteira: "whole entire",
  lista: "list",
  listagem: "listing list table",
  lixeira: "trash delete",
  longa: "long",
  longo: "long",
  manutencao: "maintenance",
  marcar: "check mark",
  mensagem: "message",
  muitos: "many",
  nascimento: "birth",
  navegacao: "navigation",
  nota: "invoice",
  notificacao: "notification",
  numero: "number",
  olho: "eye",
  opcao: "option",
  opcoes: "options",
  ordenar: "sort",
  pagina: "page",
  paginacao: "pagination",
  passo: "step",
  pedir: "request ask",
  perguntas: "questions",
  pessoa: "person",
  placa: "plate",
  preenche: "fills",
  primeira: "first",
  progresso: "progress",
  qualquer: "any",
  rascunho: "draft",
  reais: "money currency",
  revela: "reveals",
  salvar: "save",
  selecionar: "select",
  senha: "password",
  servidor: "server",
  sino: "bell",
  sozinho: "automatically",
  tabela: "table",
  teclado: "keyboard",
  telefone: "phone",
  tempo: "time",
  texto: "text",
  titulo: "title",
  uso: "usage use",
  usuario: "user",
  vazia: "empty",
  vazio: "empty",
  valor: "value amount",
  verificacao: "verification",
  volta: "undo back",
};

export function fold(text: string): string {
  return text.normalize("NFD").replace(/\p{M}/gu, "").toLowerCase();
}

export function stem(word: string): string {
  return word.length > 6 ? word.slice(0, 6) : word.replace(/s$/, "");
}

export function words(text: string): string[] {
  return fold(text).match(/[a-z0-9]+/g) ?? [];
}

export function terms(text: string): string[] {
  return words(text).filter((word) => word.length > 1 && !STOPWORDS.has(word));
}

export function stems(text: string): Set<string> {
  return new Set(terms(text).map(stem));
}

export function queryStems(text: string): Set<string> {
  const english = words(text)
    .map((word) => GLOSSARY[word])
    .filter((item): item is string => item !== undefined)
    .join(" ");
  return new Set([...stems(text), ...stems(english)]);
}

export function overlap(query: Set<string>, text: Set<string>): string[] {
  return [...query].filter((item) => text.has(item));
}

export function compact(name: string): string {
  return fold(name).replace(/[^a-z0-9]/g, "");
}

export function clip(text: string, size: number): string {
  const flat = text.replace(/\s+/g, " ").trim();
  return flat.length > size ? `${flat.slice(0, size - 1).trimEnd()}…` : flat;
}
